set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(CMAKE_C_COMPILER NAMES cl)
set(CMAKE_CXX_COMPILER "${CMAKE_C_COMPILER}")

set(CMAKE_C_FLAGS "-Wall")
set(CMAKE_CPP_FLAGS "${CMAKE_C_FLAGS}")
